In [1]:
import openstudio
import subprocess
import os
import shutil

In [1]:
import os
import shutil
import subprocess
import openstudio
import pandas as pd

def check_epw_quality(epw_path):
    """
    Perform quality checks on an EPW file and return a summary of whether each variable is 'Good' or 'Suspicious'.
    
    Parameters:
        epw_path (str): Path to the EPW file.
    
    Returns:
        dict: Dictionary with quality check results for each tested variable.
    """
    # Read EPW file (skip header, start from line 9)
    epw_df = pd.read_csv(epw_path, skiprows=8, header=None)

    # Dictionary to store check results
    quality_checks = {}

    ### 1️⃣ Check for Missing Data ###
    missing_values = epw_df.isnull().sum().sum()
    quality_checks["Missing Data"] = "Suspicious" if missing_values > 0 else "Good"

    ### 2️⃣ Enhanced Dry Bulb Temperature Checks ###
    dry_bulb_temp = epw_df[6]
    month = epw_df[1]

    # Extreme values (-50°C to 60°C)
    extreme_values = ((dry_bulb_temp < -50) | (dry_bulb_temp > 60)).any()
    quality_checks["Extreme Temperature"] = "Suspicious" if extreme_values else "Good"

    # Sudden jumps (> 15°C per hour)
    temp_diff = dry_bulb_temp.diff().abs()
    rapid_jumps = (temp_diff > 15).any()
    quality_checks["Sudden Temp Jumps"] = "Suspicious" if rapid_jumps else "Good"

    # Constant temperature for more than 12 hours
    const_periods = (dry_bulb_temp.rolling(window=12, min_periods=1).std() == 0).any()
    quality_checks["Constant Temp Periods"] = "Suspicious" if const_periods else "Good"

    # Unrealistic day-night swings (<3°C or >30°C)
    epw_df["daily_max"] = dry_bulb_temp.groupby(epw_df[2]).transform("max")
    epw_df["daily_min"] = dry_bulb_temp.groupby(epw_df[2]).transform("min")
    epw_df["daily_range"] = epw_df["daily_max"] - epw_df["daily_min"]
    unrealistic_swings = ((epw_df["daily_range"] < 3) | (epw_df["daily_range"] > 30)).any()
    quality_checks["Day-Night Swings"] = "Suspicious" if unrealistic_swings else "Good"

    # Seasonal temperature mismatches
    summer_issues = ((month.isin([6, 7, 8])) & (dry_bulb_temp < 0)).any()  # Summer months with freezing temps
    winter_issues = ((month.isin([12, 1, 2])) & (dry_bulb_temp > 40)).any()  # Winter months with extreme heat
    quality_checks["Summer Freezing"] = "Suspicious" if summer_issues else "Good"
    quality_checks["Winter Extreme Heat"] = "Suspicious" if winter_issues else "Good"

    # Missing temperature data
    missing_temps = dry_bulb_temp.isna().any()
    quality_checks["Missing Temperature Data"] = "Suspicious" if missing_temps else "Good"

    return quality_checks

def run_energyplus_simulations(year):
    input_csv = f'resources/zip_code_list_{year}.csv'
    # Load the input CSV.
    df = pd.read_csv(input_csv)
    
    # Add the "EnergyPlus Status" column if it doesn't exist.
    if "EnergyPlus Status" not in df.columns:
        df["EnergyPlus Status"] = ""
    
    # Ensure quality check columns exist.
    quality_columns = [
        "Missing Data",
        "Extreme Temperature",
        "Sudden Temp Jumps",
        "Constant Temp Periods",
        "Day-Night Swings",
        "Summer Freezing",
        "Winter Extreme Heat",
        "Missing Temperature Data"
    ]
    for col in quality_columns:
        if col not in df.columns:
            df[col] = ""
    
    # Get the unique weather station IDs.
    unique_stations = df[f"weather_station_wmo_{year}"].unique()

    # Set EnergyPlus installation location.
    energyplus_path = '/Applications/EnergyPlus-23-2-0/energyplus'
    current_directory = os.getcwd()


    print('***************')
    print(len(unique_stations))
    print('***************')

    k = 0
    for station in unique_stations:
        print(k)

        # If any row with this weather station already has a non-empty EnergyPlus Status, skip simulation.
        station_rows = df[df[f"weather_station_wmo_{year}"] == station]
        if station_rows["EnergyPlus Status"].notna().all() and (station_rows["EnergyPlus Status"] != "").all():
            k += 1
            continue

        epw_path = os.path.join(f"epws_wmo_{year}", f'{station}_{year}.epw')

        # Create (or reuse) the simulation directory.
        out_dir = "test_epws_dir"
        os.makedirs(out_dir, exist_ok=True)

        min_idf = openstudio.IdfFile().load("resources/min.idf").get()
        # Save IDF file
        min_idf.save(f"{out_dir}/in.idf", True)

        # Copy the minimal IDF file and the EPW file into the simulation directory.
        shutil.copy(epw_path, os.path.join(out_dir, "in.epw"))

        # Change directory to the simulation folder.
        os.chdir(out_dir)

        # Run EnergyPlus simulation.
        process = subprocess.run(
            [energyplus_path, "-w", "in.epw", "in.idf"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        
        # Check if the simulation ran successfully.
        status = "Good" if process.stderr.strip() == "EnergyPlus Completed Successfully." else "Bad"

        # Return to the original directory.
        os.chdir(current_directory)

        # Update simulation status for all rows corresponding to this weather station.
        df.loc[df[f"weather_station_wmo_{year}"] == station, "EnergyPlus Status"] = status

        # Run quality checks on the EPW file.
        quality_results = check_epw_quality(epw_path)
        for key, value in quality_results.items():
            df.loc[df[f"weather_station_wmo_{year}"] == station, key] = value

        # Save and reload CSV after processing each station.
        df.to_csv(input_csv, index=False)
        df = pd.read_csv(input_csv)

        k += 1

    return df

year = 2023
# Run the EnergyPlus simulations, perform EPW quality checks, and print the updated DataFrame.
final_df = run_energyplus_simulations(year)
final_df

***************
2573
***************
0
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

1
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

2
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

3
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

4
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

5
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

6
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

7
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

8
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No

/var/folders/cj/vhw1_9g1151dh76sjlgdyq19k7f3h5/T/ipykernel_60650/3070656699.py:149: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

9
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
10
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
11
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
12
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
13
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
14
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
15
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
16
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
17
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
18
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
19
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
20
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
21
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
22
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
23
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
24
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
25
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
26
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
27
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
28
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
29
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
30
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
31
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
32
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
33
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
34
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
35
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
36
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
37
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
38
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
39
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
40
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
41
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
42
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
43
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
44
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
45
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
46
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
47
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
48
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
49
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
50
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
51
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
52
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
53
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
54
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
55
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
56
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
57
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
58
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
59
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
60
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
61
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
62
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
63
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
64
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
65
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
66
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
67
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
68
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
69
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
70
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
71
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
72
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
73
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
74
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
75
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
76
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
77
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
78
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
79
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
80
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
81
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
82
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
83
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
84
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
85
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
86
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
87
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
88
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
89
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
90
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
91
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
92
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
93
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
94
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
95
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
96
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
97
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
98
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
99
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
100
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
101
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
102
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
103
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
104
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
105
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
106
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
107
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
108
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
109
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
110
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
111
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
112
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
113
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
114
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
115
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
116
[utilities.idf.IdfObject] <1> IdfObject of type 'OutputControl:Files' cannot have field index of 31. Cutting off IdfObject field parsing here, with the following text remaining:
No
117

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,...,RH_holes_2023,EnergyPlus Status,Missing Data,Extreme Temperature,Sudden Temp Jumps,Constant Temp Periods,Day-Night Swings,Summer Freezing,Winter Extreme Heat,Missing Temperature Data
0,99638,52.89995,-168.93738,Nikolski,AK,Alaska,True,NaN,26,0.5,...,False,Bad,Good,Good,Good,Suspicious,Good,Good,Good,Good
1,99923,55.97796,-130.03671,Hyder,AK,Alaska,True,NaN,15,0.4,...,False,Good,Good,Good,Good,Good,Suspicious,Good,Good,Good
2,99776,63.38825,-143.41140,Tanacross,AK,Alaska,True,NaN,141,2.6,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
3,99566,61.28097,-142.78996,Chitina,AK,Alaska,True,NaN,98,0.0,...,False,Good,Good,Good,Suspicious,Good,Suspicious,Suspicious,Good,Good
4,99780,63.19468,-143.07797,Tok,AK,Alaska,True,NaN,1559,0.5,...,False,Good,Good,Good,Suspicious,Good,Suspicious,Suspicious,Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32961,36604,30.68220,-88.06816,Mobile,AL,Alabama,True,NaN,9567,1398.1,...,False,Good,Good,Good,Good,Good,Suspicious,Good,Good,Good
32962,99753,64.93968,-161.15126,Koyuk,AK,Alaska,True,NaN,271,22.0,...,False,Bad,Good,Good,Good,Suspicious,Suspicious,Suspicious,Good,Good
32963,45871,40.49378,-84.29966,New Knoxville,OH,Ohio,True,NaN,2008,32.6,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
32964,99773,66.88758,-157.16496,Shungnak,AK,Alaska,True,NaN,288,18.6,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Suspicious,Good,Good
32965,3063,42.77951,-71.51939,Nashua,NH,New Hampshire,True,NaN,16781,798.8,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good

In [2]:
import os
import shutil
import subprocess
import openstudio
import pandas as pd

def run_energyplus_simulations(year):
    input_csv = f'resources/zip_code_list_{year}.csv'
    # Load the input CSV.
    df = pd.read_csv(input_csv)

    # Add the "EnergyPlus Status" column if it doesn't exist.
    if "EnergyPlus Status" not in df.columns:
        df["EnergyPlus Status"] = ""

    # Get the unique weather station IDs.
    unique_stations = df[f"weather_station_wmo_{year}"].unique()

    # Set EnergyPlus installation location.
    energyplus_path = '/Applications/EnergyPlus-23-2-0/energyplus'
    current_directory = os.getcwd()

    print('***************')
    print(len(unique_stations))
    print('***************')

    k = 0
    for station in unique_stations:
        print(k)
        # If any row with this weather station already has a non-empty status, skip simulation.
        station_rows = df[df[f"weather_station_wmo_{year}"] == station]
        if station_rows["EnergyPlus Status"].notna().all() and (station_rows["EnergyPlus Status"] != "").all():
            continue

        # # Create (or reuse) the simulation directory.
        out_dir = "test_epws_dir"
        shutil.copy("resources/min.idf", "test_epws_dir/in.epw")
        epw_path = os.path.join(f"epws_wmo_{year}", f'{station}_{year}.epw')
        shutil.copy(epw_path, os.path.join(out_dir, "in.epw"))

        # Change directory to the simulation folder.
        os.chdir(out_dir)

        # Run EnergyPlus simulation.
        process = subprocess.run(
            [energyplus_path, "-w", "in.epw", "in.idf"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )

        # Check if the simulation ran successfully.
        status = "Good" if process.stderr.strip() == "EnergyPlus Completed Successfully." else "Bad"
        # if status == "Bad":
        #     print(f"Errors for {station}:\n{process.stderr}")

        # Return to the original directory.
        os.chdir(current_directory)

        # Update all rows corresponding to this weather station with the simulation status.
        df.loc[df[f"weather_station_wmo_{year}"] == station, "EnergyPlus Status"] = status
        df.to_csv(input_csv, index=False)
        # Reload the CSV before moving to the next station.
        df = pd.read_csv(input_csv)

        k+=1

    return df

year = 2024
# Run the EnergyPlus simulations and print the updated DataFrame.
final_df = run_energyplus_simulations(year)
final_df

***************
1541
***************
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,...,RH_holes_2024,EnergyPlus Status,Missing Data,Extreme Temperature,Sudden Temp Jumps,Constant Temp Periods,Day-Night Swings,Summer Freezing,Winter Extreme Heat,Missing Temperature Data
0,99638,52.89995,-168.93738,Nikolski,AK,Alaska,True,NaN,26,0.5,...,True,Good,Good,Good,Good,Suspicious,Good,Good,Good,Good
1,99923,55.97796,-130.03671,Hyder,AK,Alaska,True,NaN,15,0.4,...,False,Good,Good,Good,Suspicious,Suspicious,Suspicious,Good,Good,Good
2,99776,63.38825,-143.41140,Tanacross,AK,Alaska,True,NaN,141,2.6,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
3,99566,61.28097,-142.78996,Chitina,AK,Alaska,True,NaN,98,0.0,...,False,Good,Good,Good,Suspicious,Suspicious,Suspicious,Good,Good,Good
4,99780,63.19468,-143.07797,Tok,AK,Alaska,True,NaN,1559,0.5,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23370,60302,41.89463,-87.78971,Oak Park,IL,Illinois,True,NaN,32048,4109.6,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
23371,79410,33.56969,-101.89127,Lubbock,TX,Texas,True,NaN,10160,1622.3,...,False,Good,Good,Good,Good,Good,Suspicious,Good,Good,Good
23372,76115,32.67879,-97.33076,Fort Worth,TX,Texas,True,NaN,20507,1699.2,...,False,Good,Good,Good,Good,Good,Suspicious,Good,Good,Good
23373,29684,34.38030,-82.72663,Starr,SC,South Carolina,True,NaN,3915,26.9,...,False,Good,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good
23374,33324,26.11236,-80.27416,Fort Lauderdale,FL,Florida,True,NaN,48807,2069.9,...,False,Good,Good,Good,Good,Good,Good,Good,Good,Good

Delete files

In [3]:
import pandas as pd
import os

# Define paths: update these with your actual CSV file and folder path.
csv_file = 'resources/zip_code_list_2023.csv'           # Path to your CSV file
epw_folder = 'epws_wmo_2023'  # Folder where the .epw files are stored

# Read the CSV file
df = pd.read_csv(csv_file)

# Loop over the rows where "EnergyPlus Status" is "Bad"
for idx, row in df.iterrows():
    if row['EnergyPlus Status'].strip().lower() == 'bad':
        # Assuming there's a column named "FileName" that has the file names
        file_name = row['weather_station_wmo_2023'].strip()
        file_name = file_name + '_2023.epw'
        file_path = os.path.join(epw_folder, file_name)
        
        if os.path.exists(file_path):
            os.remove(file_path)
            print(f"Deleted: {file_path}")
        else:
            print(f"File not found: {file_path}")

Deleted: epws_wmo_2023/70489_2023.epw
Deleted: epws_wmo_2023/76061_2023.epw
Deleted: epws_wmo_2023/72665_2023.epw
Deleted: epws_wmo_2023/KPHP0_2023.epw
Deleted: epws_wmo_2023/KIDA0_2023.epw
Deleted: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/72665_2023.epw
Deleted: epws_wmo_2023/KCVS0_2023.epw
Deleted: epws_wmo_2023/KCVN0_2023.epw
Deleted: epws_wmo_2023/VF54M_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
Deleted: epws_wmo_2023/KMYL0_2023.epw
Deleted: epws_wmo_2023/8NL5S_2023.epw
Deleted: epws_wmo_2023/72580_2023.epw
Deleted: epws_wmo_2023/R521S_2023.epw
File not found: epws_wmo_2023/VF54M_2023.epw
Deleted: epws_wmo_2023/70259_2023.epw
Deleted: epws_wmo_2023/72622_2023.epw
Deleted: epws_wmo_2023/KLKV0_2023.epw
Deleted: epws_wmo_2023/KSRR0_2023.epw
Deleted: epws_wmo_2023/4X77V_2023.epw
File not found: epws_wmo_2023/KPHP0_2023.epw
Deleted: epws_wmo_2023/KONO0_2023.epw
Deleted: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/KSUN0_2023.epw
Deleted: epws_wmo_2023/715W9_2023.epw
Deleted: epws_wmo_2023/FKUTW_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
Deleted: epws_wmo_2023/72683_2023.epw
Deleted: epws_wmo_2023/72266_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
Deleted: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/KPLU0_2023.epw
Deleted: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/KCVS0_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KSRR0_2023.epw
Deleted: epws_wmo_2023/MBPUU_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/72653_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
Deleted: epws_wmo_2023/U1K6U_2023.epw
Deleted: epws_wmo_2023/KCMR0_2023.epw
File not found: epws_wmo_2023/72683_2023.epw
Deleted: epws_wmo_2023/KCDR0_2023.epw
Deleted: epws_wmo_2023/8S0JF_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
Deleted: epws_wmo_2023/KCEC0_2023.epw
File not found: epws_wmo_2023/72683_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
Deleted: epws_wmo_2023/KVDW0_2023.epw
Deleted: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/72653_2023.epw
Deleted: epws_wmo_2023/KITH0_2023.epw
Deleted: epws_wmo_2023/72574_2023.epw
Deleted: epws_wmo_2023/74638_2023.epw
File not found: epws_wmo_2023/8NL5S_2023.epw
Deleted: epws_wmo_2023/70261_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
File not found: epws_wmo_2023/KITH0_2023.epw
File not found: epws_wmo_2023/74638_2023.epw
Deleted: epws_wmo_2023/KM750_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
File not found: epws_wmo_2023/KPLU0_2023.epw
Deleted: epws_wmo_2023/72743_2023.epw
File not found: epws_wmo_2023/KCVS0_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/KW220_2023.epw
Deleted: epws_wmo_2023/PAJZ0_2023.epw
Deleted: epws_wmo_2023/KAWO0_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
Deleted: epws_wmo_2023/72440_2023.epw
Deleted: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/KCVN0_2023.epw
Deleted: epws_wmo_2023/KO220_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/KAIA0_2023.epw
Deleted: epws_wmo_2023/72514_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
File not found: epws_wmo_2023/72440_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/72497_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
Deleted: epws_wmo_2023/KSPD0_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
Deleted: epws_wmo_2023/KMLP0_2023.epw
Deleted: epws_wmo_2023/KLSV0_2023.epw
File not found: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/KMLP0_2023.epw
Deleted: epws_wmo_2023/KOLF0_2023.epw
File not found: epws_wmo_2023/KONO0_2023.epw
File not found: epws_wmo_2023/KITH0_2023.epw
Deleted: epws_wmo_2023/72591_2023.epw
Deleted: epws_wmo_2023/KS250_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/72440_2023.epw
File not found: epws_wmo_2023/KCVN0_2023.epw
File not found: epws_wmo_2023/KMLP0_2023.epw
Deleted: epws_wmo_2023/KY190_2023.epw
Deleted: epws_wmo_2023/KIWD0_2023.epw
Deleted: epws_wmo_2023/KTRM0_2023.epw
File not found: epws_wmo_2023/72743_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
Deleted: epws_wmo_2023/KFNB0_2023.epw
Deleted: epws_wmo_2023/72452_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/74638_2023.epw
Deleted: epws_wmo_2023/KBZN0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/VF54M_2023.epw
Deleted: epws_wmo_2023/PAKH0_2023.epw
Deleted: epws_wmo_2023/KNBG0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/8NL5S_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
Deleted: epws_wmo_2023/5F44V_2023.epw
File not found: epws_wmo_2023/KMLP0_2023.epw
File not found: epws_wmo_2023/KSRR0_2023.epw
Deleted: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/KMLP0_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/74638_2023.epw
Deleted: epws_wmo_2023/KHFJ0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
Deleted: epws_wmo_2023/KLXN0_2023.epw
Deleted: epws_wmo_2023/K7L20_2023.epw
Deleted: epws_wmo_2023/KLNL0_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
Deleted: epws_wmo_2023/KYKN0_2023.epw
Deleted: epws_wmo_2023/KESF0_2023.epw
File not found: epws_wmo_2023/KCEC0_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
Deleted: epws_wmo_2023/70367_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
Deleted: epws_wmo_2023/KTVR0_2023.epw
File not found: epws_wmo_2023/KSUN0_2023.epw
Deleted: epws_wmo_2023/92Z76_2023.epw
Deleted: epws_wmo_2023/72412_2023.epw
File not found: epws_wmo_2023/KLNL0_2023.epw
File not found: epws_wmo_2023/KAWO0_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
Deleted: epws_wmo_2023/KVEL0_2023.epw
Deleted: epws_wmo_2023/70173_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/K20U0_2023.epw
File not found: epws_wmo_2023/KCVS0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/KPLU0_2023.epw
File not found: epws_wmo_2023/R521S_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/KONO0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
Deleted: epws_wmo_2023/QZ5US_2023.epw
File not found: epws_wmo_2023/KITH0_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
File not found: epws_wmo_2023/KY190_2023.epw
Deleted: epws_wmo_2023/KSRC0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
File not found: epws_wmo_2023/KIDA0_2023.epw
Deleted: epws_wmo_2023/KCOE0_2023.epw
File not found: epws_wmo_2023/72743_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/KCVN0_2023.epw
Deleted: epws_wmo_2023/KSTF0_2023.epw
Deleted: epws_wmo_2023/KHZE0_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
Deleted: epws_wmo_2023/KBKE0_2023.epw
File not found: epws_wmo_2023/KLKV0_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
Deleted: epws_wmo_2023/KBQP0_2023.epw
File not found: epws_wmo_2023/PAKH0_2023.epw
Deleted: epws_wmo_2023/KCKB0_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
Deleted: epws_wmo_2023/KRKR0_2023.epw
File not found: epws_wmo_2023/KLXN0_2023.epw
Deleted: epws_wmo_2023/GKW3J_2023.epw
Deleted: epws_wmo_2023/KLEB6_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
Deleted: epws_wmo_2023/KCRX0_2023.epw
File not found: epws_wmo_2023/KMYL0_2023.epw
Deleted: epws_wmo_2023/70265_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
Deleted: epws_wmo_2023/KFYG0_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KRKR0_2023.epw
Deleted: epws_wmo_2023/KSEM0_2023.epw
Deleted: epws_wmo_2023/72481_2023.epw
Deleted: epws_wmo_2023/NG9G1_2023.epw
Deleted: epws_wmo_2023/K06D0_2023.epw
Deleted: epws_wmo_2023/0NNEW_2023.epw
Deleted: epws_wmo_2023/KMBO0_2023.epw
File not found: epws_wmo_2023/72440_2023.epw
File not found: epws_wmo_2023/KCVN0_2023.epw
Deleted: epws_wmo_2023/72344_2023.epw
File not found: epws_wmo_2023/KPHP0_2023.epw
Deleted: epws_wmo_2023/KEKS0_2023.epw
Deleted: epws_wmo_2023/72446_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/72665_2023.epw
File not found: epws_wmo_2023/KMYL0_2023.epw
Deleted: epws_wmo_2023/KP690_2023.epw
Deleted: epws_wmo_2023/72713_2023.epw
File not found: epws_wmo_2023/KVDW0_2023.epw
File not found: epws_wmo_2023/KSUN0_2023.epw
Deleted: epws_wmo_2023/KFYV0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
File not found: epws_wmo_2023/KM750_2023.epw
Deleted: epws_wmo_2023/7O9W0_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
File not found: epws_wmo_2023/NG9G1_2023.epw
File not found: epws_wmo_2023/KAIA0_2023.epw
File not found: epws_wmo_2023/KMBO0_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/GKW3J_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
Deleted: epws_wmo_2023/K08D0_2023.epw
Deleted: epws_wmo_2023/Y59TE_2023.epw
File not found: epws_wmo_2023/KLKV0_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
Deleted: epws_wmo_2023/72562_2023.epw
Deleted: epws_wmo_2023/KGRN0_2023.epw
Deleted: epws_wmo_2023/VAIFP_2023.epw
Deleted: epws_wmo_2023/74736_2023.epw
File not found: epws_wmo_2023/KPHP0_2023.epw
Deleted: epws_wmo_2023/KHSP0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/72562_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
Deleted: epws_wmo_2023/SN520_2023.epw
Deleted: epws_wmo_2023/72463_2023.epw
Deleted: epws_wmo_2023/KRUG0_2023.epw
File not found: epws_wmo_2023/8NL5S_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/72514_2023.epw
File not found: epws_wmo_2023/8S0JF_2023.epw
Deleted: epws_wmo_2023/KOWI0_2023.epw
File not found: epws_wmo_2023/KYKN0_2023.epw
File not found: epws_wmo_2023/VAIFP_2023.epw
File not found: epws_wmo_2023/VAIFP_2023.epw
Deleted: epws_wmo_2023/KLAA0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
Deleted: epws_wmo_2023/KN600_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
File not found: epws_wmo_2023/72773_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
Deleted: epws_wmo_2023/KGTR0_2023.epw
Deleted: epws_wmo_2023/PAVD0_2023.epw
Deleted: epws_wmo_2023/KBVS0_2023.epw
Deleted: epws_wmo_2023/DEHT1_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
Deleted: epws_wmo_2023/KADF0_2023.epw
File not found: epws_wmo_2023/7O9W0_2023.epw
File not found: epws_wmo_2023/KMYL0_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
Deleted: epws_wmo_2023/KBVX0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
Deleted: epws_wmo_2023/210N7_2023.epw
File not found: epws_wmo_2023/KLNL0_2023.epw
File not found: epws_wmo_2023/KBVX0_2023.epw
File not found: epws_wmo_2023/210N7_2023.epw
File not found: epws_wmo_2023/FKUTW_2023.epw
Deleted: epws_wmo_2023/KIMS0_2023.epw
File not found: epws_wmo_2023/VAIFP_2023.epw
File not found: epws_wmo_2023/U1K6U_2023.epw
File not found: epws_wmo_2023/72653_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/KBZN0_2023.epw
File not found: epws_wmo_2023/VAIFP_2023.epw
Deleted: epws_wmo_2023/KWLD0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/KYKN0_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/KITH0_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/Y59TE_2023.epw
Deleted: epws_wmo_2023/KLHB0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
Deleted: epws_wmo_2023/KHST0_2023.epw
Deleted: epws_wmo_2023/72315_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
Deleted: epws_wmo_2023/KS320_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KSPD0_2023.epw
Deleted: epws_wmo_2023/KMHK0_2023.epw
Deleted: epws_wmo_2023/KARG0_2023.epw
File not found: epws_wmo_2023/72315_2023.epw
File not found: epws_wmo_2023/KONO0_2023.epw
Deleted: epws_wmo_2023/72764_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
Deleted: epws_wmo_2023/KIRK0_2023.epw
File not found: epws_wmo_2023/210N7_2023.epw
File not found: epws_wmo_2023/KPHP0_2023.epw
Deleted: epws_wmo_2023/72332_2023.epw
File not found: epws_wmo_2023/72514_2023.epw
File not found: epws_wmo_2023/KYKN0_2023.epw
Deleted: epws_wmo_2023/74759_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
Deleted: epws_wmo_2023/72242_2023.epw
Deleted: epws_wmo_2023/71607_2023.epw
Deleted: epws_wmo_2023/K46D0_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
Deleted: epws_wmo_2023/KCLS0_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/QZ5US_2023.epw
File not found: epws_wmo_2023/715W9_2023.epw
Deleted: epws_wmo_2023/KPTV0_2023.epw
File not found: epws_wmo_2023/KGLY0_2023.epw
File not found: epws_wmo_2023/KMHK0_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
File not found: epws_wmo_2023/71607_2023.epw
File not found: epws_wmo_2023/72440_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
File not found: epws_wmo_2023/KTVR0_2023.epw
File not found: epws_wmo_2023/KAWO0_2023.epw
Deleted: epws_wmo_2023/KRTS0_2023.epw
File not found: epws_wmo_2023/72452_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/72315_2023.epw
File not found: epws_wmo_2023/KBQP0_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/KESF0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/KS250_2023.epw
File not found: epws_wmo_2023/71607_2023.epw
File not found: epws_wmo_2023/KTVR0_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/KFKL0_2023.epw
Deleted: epws_wmo_2023/KNRN0_2023.epw
File not found: epws_wmo_2023/KBKE0_2023.epw
Deleted: epws_wmo_2023/KHTH0_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
Deleted: epws_wmo_2023/KMCE0_2023.epw
File not found: epws_wmo_2023/72514_2023.epw
File not found: epws_wmo_2023/72315_2023.epw
File not found: epws_wmo_2023/MBPUU_2023.epw
File not found: epws_wmo_2023/KCKB0_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
File not found: epws_wmo_2023/72440_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/KARG0_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
Deleted: epws_wmo_2023/UO0HZ_2023.epw
File not found: epws_wmo_2023/92Z76_2023.epw
File not found: epws_wmo_2023/KFAM0_2023.epw
Deleted: epws_wmo_2023/70104_2023.epw
File not found: epws_wmo_2023/8S0JF_2023.epw
File not found: epws_wmo_2023/72562_2023.epw
File not found: epws_wmo_2023/72574_2023.epw
Deleted: epws_wmo_2023/PALJ0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/QZ5US_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
Deleted: epws_wmo_2023/KAKO0_2023.epw
Deleted: epws_wmo_2023/74545_2023.epw
File not found: epws_wmo_2023/BN2KA_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
Deleted: epws_wmo_2023/KDTN0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
File not found: epws_wmo_2023/XPORT_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
File not found: epws_wmo_2023/72622_2023.epw
File not found: epws_wmo_2023/KHTH0_2023.epw
Deleted: epws_wmo_2023/KBBW0_2023.epw
Deleted: epws_wmo_2023/72436_2023.epw
Deleted: epws_wmo_2023/5KQCG_2023.epw
Deleted: epws_wmo_2023/72532_2023.epw
File not found: epws_wmo_2023/72665_2023.epw
File not found: epws_wmo_2023/KCVS0_2023.epw
File not found: epws_wmo_2023/KCKB0_2023.epw
Deleted: epws_wmo_2023/KDKR0_2023.epw
File not found: epws_wmo_2023/KIRK0_2023.epw
File not found: epws_wmo_2023/KAIA0_2023.epw
File not found: epws_wmo_2023/72514_2023.epw
Deleted: epws_wmo_2023/72639_2023.epw
File not found: epws_wmo_2023/72414_2023.epw
Deleted: epws_wmo_2023/KLIC0_2023.epw
File not found: epws_wmo_2023/74545_2023.epw
File not found: epws_wmo_2023/K08D0_2023.epw
File not found: epws_wmo_2023/KONO0_2023.epw
File not found: epws_wmo_2023/KLHB0_2023.epw
File not found: epws_wmo_2023/KESF0_2023.epw
File not found: epws_wmo_2023/VAIFP_2023.epw
File not found: epws_wmo_2023/LVT9Y_2023.epw
File not found: epws_wmo_2023/5KQCG_2023.epw
Deleted: epws_wmo_2023/KCWC0_2023.epw
File not found: epws_wmo_2023/4X77V_2023.epw
File not found: epws_wmo_2023/UO0HZ_2023.epw
File not found: epws_wmo_2023/KVEL0_2023.epw
File not found: epws_wmo_2023/KVDW0_2023.epw
File not found: epws_wmo_2023/KFNB0_2023.epw
File not found: epws_wmo_2023/72779_2023.epw
File not found: epws_wmo_2023/KYKN0_2023.epw
File not found: epws_wmo_2023/KADF0_2023.epw
File not found: epws_wmo_2023/72446_2023.epw
File not found: epws_wmo_2023/KCRX0_2023.epw
File not found: epws_wmo_2023/KSCH0_2023.epw
Deleted: epws_wmo_2023/4V5MO_2023.epw
File not found: epws_wmo_2023/KCDR0_2023.epw
Deleted: epws_wmo_2023/72586_2023.epw
File not found: epws_wmo_2023/KONO0_2023.epw
File not found: epws_wmo_2023/GKW3J_2023.epw
File not found: epws_wmo_2023/KIRK0_2023.epw
File not found: epws_wmo_2023/72463_2023.epw
File not found: epws_wmo_2023/5F44V_2023.epw
File not found: epws_wmo_2023/KYKN0_2023.epw
Deleted: epws_wmo_2023/KMHL0_2023.epw
File not found: epws_wmo_2023/UO0HZ_2023.epw
File not found: epws_wmo_2023/KESF0_2023.epw
File not found: epws_wmo_2023/72452_2023.epw
File not found: epws_wmo_2023/72764_2023.epw
File not found: epws_wmo_2023/KRTS0_2023.epw
File not found: epws_wmo_2023/KCDR0_2023.epw
Deleted: epws_wmo_2023/KUOX0_2023.epw
Deleted: epws_wmo_2023/KJWG0_2023.epw
File not found: epws_wmo_2023/KW220_2023.epw
File not found: epws_wmo_2023/KTVR0_2023.epw
Deleted: epws_wmo_2023/P1E8Y_2023.epw
Deleted: epws_wmo_2023/KBWG0_2023.epw
Deleted: epws_wmo_2023/KOEL0_2023.epw
File not found: epws_wmo_2023/P1E8Y_2023.epw
File not found: epws_wmo_2023/KCVS0_2023.epw
Deleted: epws_wmo_2023/70277_2023.epw
Deleted: epws_wmo_2023/KIML0_2023.epw
File not found: epws_wmo_2023/1CZCV_2023.epw
Deleted: epws_wmo_2023/KFFL0_2023.epw
File not found: epws_wmo_2023/KJWG0_2023.epw
File not found: epws_wmo_2023/KUOX0_2023.epw
File not found: epws_wmo_2023/0NNEW_2023.epw

In [1]:
import os
import shutil
import subprocess
import openstudio
import pandas as pd
import numpy as np
import sys
import glob

def check_epw_quality(epw_path):
    """
    Perform quality checks on an EPW file and return a summary of whether each variable is 'Good' or 'Suspicious'.
    
    Parameters:
        epw_path (str): Path to the EPW file.
    
    Returns:
        dict: Dictionary with quality check results for each tested variable.
    """
    # Read EPW file (skip header, start from line 9)
    epw_df = pd.read_csv(epw_path, skiprows=8, header=None)

    # Dictionary to store check results
    quality_checks = {}

    ### 1️⃣ Check for Missing Data ###
    missing_values = epw_df.isnull().sum().sum()
    quality_checks["Missing Data"] = "Suspicious" if missing_values > 0 else "Good"

    ### 2️⃣ Enhanced Dry Bulb Temperature Checks ###
    dry_bulb_temp = epw_df[6]
    month = epw_df[1]

    # Extreme values (-50°C to 60°C)
    extreme_values = ((dry_bulb_temp < -50) | (dry_bulb_temp > 60)).any()
    quality_checks["Extreme Temperature"] = "Suspicious" if extreme_values else "Good"

    # Sudden jumps (> 15°C per hour)
    temp_diff = dry_bulb_temp.diff().abs()
    rapid_jumps = (temp_diff > 15).any()
    quality_checks["Sudden Temp Jumps"] = "Suspicious" if rapid_jumps else "Good"

    # Constant temperature for more than 12 hours
    const_periods = (dry_bulb_temp.rolling(window=12, min_periods=1).std() == 0).any()
    quality_checks["Constant Temp Periods"] = "Suspicious" if const_periods else "Good"

    # Unrealistic day-night swings (<3°C or >30°C)
    epw_df["daily_max"] = dry_bulb_temp.groupby(epw_df[2]).transform("max")
    epw_df["daily_min"] = dry_bulb_temp.groupby(epw_df[2]).transform("min")
    epw_df["daily_range"] = epw_df["daily_max"] - epw_df["daily_min"]
    unrealistic_swings = ((epw_df["daily_range"] < 3) | (epw_df["daily_range"] > 30)).any()
    quality_checks["Day-Night Swings"] = "Suspicious" if unrealistic_swings else "Good"

    # Seasonal temperature mismatches
    summer_issues = ((month.isin([6, 7, 8])) & (dry_bulb_temp < 0)).any()  # Summer months with freezing temps
    winter_issues = ((month.isin([12, 1, 2])) & (dry_bulb_temp > 40)).any()  # Winter months with extreme heat
    quality_checks["Summer Freezing"] = "Suspicious" if summer_issues else "Good"
    quality_checks["Winter Extreme Heat"] = "Suspicious" if winter_issues else "Good"

    # Missing temperature data
    missing_temps = dry_bulb_temp.isna().any()
    quality_checks["Missing Temperature Data"] = "Suspicious" if missing_temps else "Good"

    return quality_checks


def check_final_epws(year):
    # File paths for input and intermediate (processed) CSVs
    input_csv = f'resources/zip_code_list_{year}.csv'
    processed_csv = f'resources/zip_code_list_{year}_processed.csv'

    # If a processed file exists, load it; otherwise load the original file.
    if os.path.exists(processed_csv):
        zip_code_list = pd.read_csv(processed_csv)
    else:
        zip_code_list = pd.read_csv(input_csv)

    # Folder containing EPW files
    epw_folder = f"epws_wmo_{year}"
    # set energyplus installation location
    energyplus_path = '/Applications/EnergyPlus-23-2-0/energyplus'

    current_directory = os.getcwd()

    # Process each EPW file from the DataFrame
    for index, row in zip_code_list.iterrows():
        # Skip if EnergyPlus Status already exists and is non-empty.
        if pd.notna(row.get("EnergyPlus Status")) and row.get("EnergyPlus Status") != "":
            continue

        epw_filename = row[f"weather_station_wmo_{year}"]
        epw_path = os.path.join(epw_folder, f'{epw_filename}_{year}.epw')
        # Skip if file doesn't exist
        if not os.path.exists(epw_path):
            print(f"❌ File not found: {epw_path}. Skipping...")
            zip_code_list.at[index, "EnergyPlus Status"] = "File Not Found"
            # Save progress after each row update
            zip_code_list.to_csv(processed_csv, index=False)
            continue

        # Run EPW quality checks
        quality_checks = check_epw_quality(epw_path)

        # Add quality check results into the DataFrame
        for key, value in quality_checks.items():
            zip_code_list.at[index, key] = value

        # Silence OpenStudio logging while loading the IDF
        devnull = open(os.devnull, 'w')
        old_stdout, old_stderr = os.dup(1), os.dup(2)  # Save original stdout/stderr
        os.dup2(devnull.fileno(), 1)  # Redirect stdout to devnull
        os.dup2(devnull.fileno(), 2)  # Redirect stderr to devnull

        try:
            min_idf = openstudio.IdfFile().load("resources/min.idf").get()
        finally:
            os.dup2(old_stdout, 1)  # Restore stdout
            os.dup2(old_stderr, 2)  # Restore stderr
            try:
                devnull.close()  # Close devnull
            except RuntimeError:
                print(epw_path)

        # Define output directory
        out_dir = "test_epws_dir"
        os.makedirs(out_dir, exist_ok=True)  # Ensure the directory exists

        # Save IDF file
        min_idf.save(f"{out_dir}/in.idf", True)

        # Save EPW file
        shutil.copy(epw_path, f"{out_dir}/in.epw")

        # Change to IDF directory
        os.chdir(out_dir)

        # Run EnergyPlus as a subprocess
        process = subprocess.run(
            [energyplus_path, "-w", "in.epw", "in.idf"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,  # Ensure text output for easier processing
        )

        # Determine if EnergyPlus run was successful
        status = "Good" if process.stderr.strip() == "EnergyPlus Completed Successfully." else "Bad"

        # Store the EnergyPlus status in the DataFrame
        zip_code_list.at[index, "EnergyPlus Status"] = status

        # Print errors only if run failed
        if status == "Bad":
            print(f"Errors for {epw_filename}:\n{process.stderr}")

        # Change back to main directory
        os.chdir(current_directory)

        # Save progress after processing each EPW file.
        zip_code_list.to_csv(processed_csv, index=False)

    return zip_code_list


year = 2022
# Process the EPW files and print the final DataFrame with updated checks
final = check_final_epws(year)
final

KeyboardInterrupt:

In [1]:
import os
import shutil
import subprocess
import openstudio
import pandas as pd
import numpy as np
import sys
import glob

def check_epw_quality(epw_path):
    """
    Perform quality checks on an EPW file and return a summary of whether each variable is 'Good' or 'Suspicious'.
    
    Parameters:
        epw_path (str): Path to the EPW file.
    
    Returns:
        dict: Dictionary with quality check results for each tested variable.
    """
    # Read EPW file (skip header, start from line 9)
    epw_df = pd.read_csv(epw_path, skiprows=8, header=None)

    # Dictionary to store check results
    quality_checks = {}

    ### 1️⃣ Check for Missing Data ###
    missing_values = epw_df.isnull().sum().sum()
    quality_checks["Missing Data"] = "Suspicious" if missing_values > 0 else "Good"

    ### 2️⃣ Enhanced Dry Bulb Temperature Checks ###
    dry_bulb_temp = epw_df[6]
    month = epw_df[1]

    # Extreme values (-50°C to 60°C)
    extreme_values = ((dry_bulb_temp < -50) | (dry_bulb_temp > 60)).any()
    quality_checks["Extreme Temperature"] = "Suspicious" if extreme_values else "Good"

    # Sudden jumps (> 15°C per hour)
    temp_diff = dry_bulb_temp.diff().abs()
    rapid_jumps = (temp_diff > 15).any()
    quality_checks["Sudden Temp Jumps"] = "Suspicious" if rapid_jumps else "Good"

    # Constant temperature for more than 12 hours
    const_periods = (dry_bulb_temp.rolling(window=12, min_periods=1).std() == 0).any()
    quality_checks["Constant Temp Periods"] = "Suspicious" if const_periods else "Good"

    # Unrealistic day-night swings (<3°C or >30°C)
    epw_df["daily_max"] = dry_bulb_temp.groupby(epw_df[2]).transform("max")
    epw_df["daily_min"] = dry_bulb_temp.groupby(epw_df[2]).transform("min")
    epw_df["daily_range"] = epw_df["daily_max"] - epw_df["daily_min"]
    unrealistic_swings = ((epw_df["daily_range"] < 3) | (epw_df["daily_range"] > 30)).any()
    quality_checks["Day-Night Swings"] = "Suspicious" if unrealistic_swings else "Good"

    # Seasonal temperature mismatches
    summer_issues = ((month.isin([6, 7, 8])) & (dry_bulb_temp < 0)).any()   # Summer months with freezing temps
    winter_issues = ((month.isin([12, 1, 2])) & (dry_bulb_temp > 40)).any() # Winter months with extreme heat
    quality_checks["Summer Freezing"] = "Suspicious" if summer_issues else "Good"
    quality_checks["Winter Extreme Heat"] = "Suspicious" if winter_issues else "Good"

    # Missing temperature data
    missing_temps = dry_bulb_temp.isna().any()
    quality_checks["Missing Temperature Data"] = "Suspicious" if missing_temps else "Good"

    return quality_checks


def check_final_epws(year):
    # File paths for input and intermediate (processed) CSVs
    input_csv = f'resources/zip_code_list_{year}.csv'
    processed_csv = f'resources/zip_code_list_{year}_processed.csv'

    # If a processed file exists, load it; otherwise load the original file.
    if os.path.exists(processed_csv):
        zip_code_list = pd.read_csv(processed_csv)
    else:
        zip_code_list = pd.read_csv(input_csv)

    # Folder containing EPW files
    epw_folder = f"epws_wmo_{year}"
    # set energyplus installation location
    energyplus_path = '/Applications/EnergyPlus-23-2-0/energyplus'

    current_directory = os.getcwd()

    # Process each EPW file from the DataFrame
    for index, row in zip_code_list.iterrows():
        status_value = row.get("EnergyPlus Status")

        # Only process rows where "EnergyPlus Status" is NaN or "Bad"
        # If it's anything else (e.g., "Good", "File Not Found"), skip it.
        if not (pd.isna(status_value) or status_value == "Bad"):
            continue

        epw_filename = row.get(f"weather_station_wmo_{year}")
        if not isinstance(epw_filename, str):
            # If there's no valid EPW filename, skip
            zip_code_list.at[index, "EnergyPlus Status"] = "Invalid EPW Filename"
            zip_code_list.to_csv(processed_csv, index=False)
            continue

        epw_path = os.path.join(epw_folder, f'{epw_filename}_{year}.epw')

        # Skip if file doesn't exist
        if not os.path.exists(epw_path):
            print(f"❌ File not found: {epw_path}. Skipping...")
            zip_code_list.at[index, "EnergyPlus Status"] = "File Not Found"
            # Save progress after each row update
            zip_code_list.to_csv(processed_csv, index=False)
            continue

        # Run EPW quality checks
        quality_checks = check_epw_quality(epw_path)

        # Add quality check results into the DataFrame
        for key, value in quality_checks.items():
            zip_code_list.at[index, key] = value

        # Silence OpenStudio logging while loading the IDF
        devnull = open(os.devnull, 'w')
        old_stdout, old_stderr = os.dup(1), os.dup(2)  # Save original stdout/stderr
        os.dup2(devnull.fileno(), 1)  # Redirect stdout to devnull
        os.dup2(devnull.fileno(), 2)  # Redirect stderr to devnull

        try:
            min_idf = openstudio.IdfFile().load("resources/min.idf").get()
        finally:
            # Restore stdout and stderr
            os.dup2(old_stdout, 1)
            os.dup2(old_stderr, 2)
            try:
                devnull.close()
            except RuntimeError:
                print(epw_path)

        # Define output directory
        out_dir = "test_epws_dir"
        os.makedirs(out_dir, exist_ok=True)  # Ensure the directory exists

        # Save IDF file
        min_idf.save(f"{out_dir}/in.idf", True)

        # Save EPW file
        shutil.copy(epw_path, f"{out_dir}/in.epw")

        # Change to IDF directory
        os.chdir(out_dir)

        # Run EnergyPlus as a subprocess
        process = subprocess.run(
            [energyplus_path, "-w", "in.epw", "in.idf"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,  # Ensure text output for easier processing
        )

        # Determine if EnergyPlus run was successful
        status = "Good" if process.stderr.strip() == "EnergyPlus Completed Successfully." else "Bad"

        # Store the EnergyPlus status in the DataFrame
        zip_code_list.at[index, "EnergyPlus Status"] = status

        # Print errors only if run failed
        if status == "Bad":
            print(f"Errors for {epw_filename}:\n{process.stderr}")

        # Change back to main directory
        os.chdir(current_directory)

        # Save progress after processing each EPW file.
        zip_code_list.to_csv(processed_csv, index=False)

    return zip_code_list


# Example usage:
year = 2022
# Process the EPW files and print the final DataFrame with updated checks
final = check_final_epws(year)
final

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,...,RH_holes_2022,Missing Data,Extreme Temperature,Sudden Temp Jumps,Constant Temp Periods,Day-Night Swings,Summer Freezing,Winter Extreme Heat,Missing Temperature Data,EnergyPlus Status
0,99638,52.89995,-168.93738,Nikolski,AK,Alaska,True,NaN,26,0.5,...,False,Good,Good,Good,Suspicious,Good,Good,Good,Good,Good
1,99923,55.97796,-130.03671,Hyder,AK,Alaska,True,NaN,15,0.4,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good
2,99776,63.38825,-143.41140,Tanacross,AK,Alaska,True,NaN,141,2.6,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good
3,99566,61.28097,-142.78996,Chitina,AK,Alaska,True,NaN,98,0.0,...,False,Good,Good,Suspicious,Good,Suspicious,Good,Good,Good,Good
4,99780,63.19468,-143.07797,Tok,AK,Alaska,True,NaN,1559,0.5,...,False,Good,Good,Suspicious,Good,Suspicious,Good,Good,Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12721,28775,35.01980,-83.32836,Scaly Mountain,NC,North Carolina,True,NaN,267,10.5,...,False,Good,Good,Good,Good,Suspicious,Good,Good,Good,Good
12722,70817,30.37601,-90.98090,Baton Rouge,LA,Louisiana,True,NaN,35142,527.9,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good
12723,29123,33.76637,-81.25947,Pelion,SC,South Carolina,True,NaN,8525,47.6,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good
12724,25067,38.19767,-81.42894,East Bank,WV,West Virginia,True,NaN,1184,84.4,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good
12725,77003,29.74932,-95.34582,Houston,TX,Texas,True,NaN,9876,1502.0,...,False,Good,Good,Good,Suspicious,Suspicious,Good,Good,Good,Good